name: user-cd

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: fga-eps-mds/2022-2-schedula-gestor-de-usuarios/.github/workflows/user-ci.yml@main
  build:
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          dockerfile_directory: ./

          dockerfile_name: Dockerfile

          docker_options: "--no-cache"

          process_type: web       